RestaurantManagement/Models/Item.cs
namespace RestaurantManagement.Models
{
    public class Item
    {
        public int ItemId { get; set; } 
        public string ItemName { get; set; }
        public string Catagory { get; set; }
        public int Price { get; set; }
    }
}
//

RestaurantManagement/Controllers/ItemController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using RestaurantManagement.Data;
using RestaurantManagement.Models;
//home page

namespace RestaurantManagement.Controllers
{
    public class ItemController : Controller
    {
        private readonly ApplicationDbContext _context;
        
        // clear after submit
        static List<OrderItem> OItems = new List<OrderItem>();
        static bool isEmptyOrderList = false;
        static string _categoryType = null;
        static Order orderDetails = new Order();
        public ItemController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var Items_ = new List<Item>();
            if(_categoryType == null )
            {
                Items_ = _context.Items.ToList();
            } else
            {
                Items_ = _context.Items.ToList().FindAll(m => String.Compare(m.Catagory, _categoryType) == 0);
            }

            ViewBag.orderedItems = OItems;
            ViewBag.isEmptyOrderList = isEmptyOrderList;

            return View(Items_);           
        }

        public IActionResult addItem(string item, int quantity)
        {
            var item_ = _context.Items
               .FirstOrDefault(m => m.ItemName == item);

            var newItem = new OrderItem(){
                OrderedItem = item,
                Quantity = quantity,
                UnitPrice = item_.Price,
            };

            OItems.Add(newItem);

            isEmptyOrderList = false;
            return RedirectToAction(nameof(Index));
        }

        public IActionResult RemoveOrderedItem(string ItemName, int ItemQua)
        {
            var ItemToRemove = OItems.First(i => i.OrderedItem == ItemName && i.Quantity == ItemQua);
            OItems.Remove(ItemToRemove);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult AddOrder(string customerName, string delivery)
        {

          
            //create Order
            //OrderItems, OrderType, CustomerName, OrderStatus, PaymentStatus
            var OStatus = false;
            if(delivery == "Dine In")
            {
                OStatus = true;
            }

            var newOrder = new Order() {
                OrderItems = OItems,
                OrderType = delivery,
                CustomerName = customerName,
                OrderStatus = OStatus,
                PaymentStatus = OStatus,
                OrderDate = DateTime.Now,
            };

            // add & save Order to database
            _context.Orders.Add(newOrder);
            _context.SaveChanges();

            // empty the OItem list
            
            isEmptyOrderList = false;
            orderDetails = newOrder;

            return RedirectToAction(nameof(ViewBill));
             
        }

        public IActionResult ViewAllOrders()
        {
            var AllOrders = _context.Orders.ToList();
            return View(AllOrders);
        }

        public IActionResult ViewPendingOrders()
        {
            var pendingOrders = _context.Orders.ToList().FindAll(m => m.OrderStatus == false);
            return View(pendingOrders);
        }

        public IActionResult changeOrderStatus(int orderId)
        {
            var order = _context.Orders.First(m => m.OrderId == orderId);
            order.OrderStatus = true;
            _context.Orders.Update(order);
            _context.SaveChanges();

            return RedirectToAction(nameof(ViewPendingOrders));
        }


        public IActionResult ViewPendingPayments()
        {
            var pendingPayments = _context.Orders.ToList().FindAll(m => m.PaymentStatus == false);
            return View(pendingPayments);
        }

        public IActionResult changePaymentStatus(int orderId)
        {
            var order = _context.Orders.First(m => m.OrderId == orderId);
            order.PaymentStatus = true;
            _context.Orders.Update(order);
            _context.SaveChanges();

            return RedirectToAction(nameof(ViewPendingPayments));
        }

        public IActionResult ViewBill()
        {
            // check for the empty OList
            if (OItems.Count == 0)
            {
                isEmptyOrderList = true;
                return RedirectToAction(nameof(Index));
               
            }

            Order ord = orderDetails;
            ViewBag.ordItems = ord.OrderItems.ToList();
            orderDetails = null;
            OItems.Clear();
            _categoryType = null;
            return View(ord);
        }

        
        public IActionResult Temp(string categoryType)
        {
            _categoryType = categoryType;
            return RedirectToAction(nameof(Index));
        }
        public IActionResult AddNewItem()
        {
            var newItem = new Item();
            return View(newItem);
        }
        public IActionResult AddItemHelper(Item newItem)
        {
            _context.Items.Add(newItem);
            _context.SaveChanges();
            return RedirectToAction(nameof(AddNewItem));
        }

        public IActionResult ViewAllItems()
        {
            //categories:
            // Soup, Starter, Dessert, Beverages
            //var allItems = _context.Items.ToList();

            var Soup = _context.Items.ToList().FindAll(m => String.Compare(m.Catagory, "Soup") == 0);
            var MainCourse = _context.Items.ToList().FindAll(m => m.Catagory == "Main course");
            var Starter = _context.Items.ToList().FindAll(m => m.Catagory == "Starter");
            var Dessert = _context.Items.ToList().FindAll(m => m.Catagory == "Dessert");
            var Beverages = _context.Items.ToList().FindAll(m => String.Compare(m.Catagory, "Beverages") == 0);

            ViewBag.Soup = Soup;
            ViewBag.MainCourse = MainCourse;
            ViewBag.Starter = Starter;
            ViewBag.Dessert = Dessert;
            ViewBag.Beverages = Beverages;

            return View();
            
        }

        public IActionResult DeleteItem(int itemId)
        {
            var item = _context.Items.Find(itemId);
            if(item != null)
            {
                _context.Items.Remove(item);
                _context.SaveChanges();
            }
            return RedirectToAction(nameof(ViewAllItems));
        }
    }
}   

RestaurantManagement/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using RestaurantManagement.Data;
using RestaurantManagement.Models;
//user page

namespace RestaurantManagement.Controllers
{
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _context;

        public UserController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()

        {
            return View();
        }

        
        public IActionResult Create()
        {
            User user = new User();
            return View(user);
        }
        

        public IActionResult CreateUser(User usr)
        {
            _context.Users.Add(usr);
            _context.SaveChanges();

            HttpContext.Session.SetString("SUserName", usr.UserName);
            HttpContext.Session.SetString("SUserId", usr.UserId.ToString());
            return RedirectToAction(nameof(Index));
        }

        public IActionResult ViewUsers()
        {
            List<User> users = new List<User>();
            users = _context.Users.ToList();
            return View(users);
        }

        public IActionResult DeleteUser(int userId)
        {
            User usr = _context.Users.Find(userId);
            if (usr != null)
            {
                _context.Users.Remove(usr);
                _context.SaveChanges();
            }

            return RedirectToAction(nameof(ViewUsers));
        }

        public IActionResult Login()
        {
            return View();
        }

        public IActionResult LoginUser(string userEmail, string userPassword)
        {
            //var user = _context.Users.;
            var user =  _context.Users
                .FirstOrDefault(m => m.Email == userEmail && m.Password == userPassword);

            if(user != null)
            {
                // setting session for login
                HttpContext.Session.SetString("SUserName", user.UserName);
                HttpContext.Session.SetString("SUserId", user.UserId.ToString());

                return RedirectToAction(nameof(Index));
            }
            else
            {
                ViewBag.errMsg = "No Such User Found";
                return View("Login");
            }
        }

        public IActionResult Logout()
        {
            // delete session info
            HttpContext.Session.Clear();

            return RedirectToAction(nameof(Index));
        }
    }
}

RestaurantManagement/Views/Item/AddNewItem.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor Accessor

@model Item

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@if(Accessor.HttpContext.Session.GetString("SUserName") != null)
{
    
    <div class="row">
        <div class="col-6">
            <form asp-controller="Item" asp-action="AddItemHelper" asp-action="post">
              <div class="mb-3">
                <label for="ItemName" class="form-label">Item Name</label>
                <input asp-for="ItemName" type="text" class="form-control" id="ItemName">
              </div>

              <!--
              <div class="mb-3">
                <label for="Catagory" class="form-label">Category</label>
                <input asp-for="Catagory" type="string" class="form-control" id="Catagory">
              </div>
              -->

              <select asp-for="Catagory" class="form-select" aria-label="Default select example">
                  <option selected disabled>Select Category</option>
                  <option value="Soup">Soup</option>
                  <option value="Starter">Starter</option>
                  <option value="Main course">Main Course</option>
                  <option value="Dessert">Dessert</option>
                  <option value="Beverages">Beverages</option>
              </select>

              <div class="mb-3">
                <label for="price" class="form-label">Price</label>
                <input asp-for="Price" type="number" class="form-control" id="price">
              </div>
          
              <button type="submit" class="btn btn-primary">Add Item</button>
            </form>
        </div>

    </div>
}
else {
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <strong>Please Login...</strong>
       <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}
//

RestaurantManagement/Views/Item/Index.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor Accessor

@model List<Item>

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<style>
    .hidden {
        display:none;
    }
</style>



@if(ViewBag.isEmptyOrderList == true)
{

    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <strong>No Order Items</strong>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>

}

@if(Accessor.HttpContext.Session.GetString("SUserName") != null)
{
    
    <fieldset class="m-3">
        <legend>Restaurant</legend>
        <div class="container">
            <form asp-controller="Item" asp-action="addItem" method="post" >
            <div class="row">
                <!-- New -->
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="category">Category:</label>
                            <div class="form-group">
                                <select name="category" id="category" onchange="changeItems(this)">  
                                
                                    <option disabled selected>Select category</option>
                                    <option value="Soup">Soup</option>
                                    <option value="Main course">Main Course</option>
                                    <option value="Starter">Starter</option>
                                    <option value="Dessert">Dessert</option>
                                    <option value="Beverages">Beverages</option>
                                
                                </select>
                            </div>
                    </div>
                </div>
                <!-- -->
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="items">Items:</label>
                            <div class="form-group">
                                <select name="item" id="items">
                              
                                    @foreach(var item in @Model)
                                    {
                                        <option value="@item.ItemName">@item.ItemName</option>
                                    }
                                </select>
                            </div>
                    </div>
                </div>

                <div class="col-md-4">
                    Quantity:
                    <input type="number" name="quantity" id="quantity" min="1" max="20"/>
                </div>
            </div>

            <input type="submit" name="submit" value="Add Item" class="mt-3"/>
            </form>

        


        </div>
    </fieldset>

    <fieldset class="m-3">
        <legend>Customer Details</legend>
            <div class="container">
                <form asp-controller="Item" asp-action="AddOrder" method="post" >
                    <div class="row">

                        <!-- Hidden fields
                        <input type="hidden" name="orderStatus" value="0" />
                        <input type="hidden" name="paymentStatus" value="0" />
                            -->

                        <div class="col-md-4">
                            <div class="form-group">
                    
                                <input type="text" name="customerName" id="CustomerName" class="form-control" placeholder="Customer Name" required/>
                            </div>
                        </div>
                     
                        <!--
                            <div class="col-md-4">
                                <div class="form-group select-table">
                                    <label for="TableNo">Table No</label>
                                    <select name="tableNo" id="TableNo" >
                                        <option value="1">1</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                        <option value="4">4</option>
                                        <option value="5">5</option>
                                        <option value="6">6</option>
                                        <option value="7">7</option>
                                        <option value="8">8</option>
                                        <option value="9">9</option>
                                        <option value="10">10</option>
                               
                                    </select>
                                </div>
                            </div>
                        -->

                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="delivery">Delivery Type:</label>
                                <select name="delivery" id="delivery" onchange="isTable(this)">
                                    <option value="Dine In">Dine In</option>
                                    <option value="Take Away">Take Away</option>
                               
                                </select>
                            </div>
                        </div>

                    </div>
                    
                    <input type="submit" name="order" value="order" class="mt-3"/>
                </form>
            </div>
        
    </fieldset>

    <div class="m-3" style="overflow:auto" height="50px">

        <table class="table table-striped" >
            <thead>
                <tr>
                    <th>Item Name</th>
                    <th>Quantity</th>
                    <th>Unit Price</th>
                    <th>Action</th>
                </tr>
            </thead>
        @if(ViewBag.orderedItems != null)
        {
            @foreach(var item in ViewBag.orderedItems)
            {
                <tr>
                    <td>@item.OrderedItem</td>
                    <td>@item.Quantity</td>
                    <td>@item.UnitPrice</td>

                    <td>
                        <form asp-controller="Item" asp-action="RemoveOrderedItem" method="post">
                            <input type="hidden" name="ItemName" value="@item.OrderedItem">
                            <input type="hidden" name="ItemQua" value="@item.Quantity">
                            <button type="submit" class="btn btn-primary">Remove</button>                   
                        </form>
                    </td>
                </tr>
            }
        }
        </table>
    </div>
}
else {
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <strong>Please Login...</strong>
       <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

<script>
    
    function isTable(obj) {
        var val = obj.value;
		if(val == "Take Away") {
            document.querySelector(".select-table").classList.add("hidden");
        }
    }

    function changeItems(obj) {
        
        /*
        $.ajax({
            type: 'GET',
            dataType: 'JSON',
            contentType: 'application/json; charset=utf-8',
            data: {categoryType: obj.value },
            url: '/item/Temp',
            success: function () { 
               
            },
            
        });
        */

       window.location.href = "/item/Temp?categoryType=" + obj.value;
    } 
</script>
//

RestaurantManagement/Views/Item/ViewAllItems.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor Accessor




@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
 
}
@if(Accessor.HttpContext.Session.GetString("SUserName") != null)
{
    
    <table class="table table-striped">

        <thead>
            <tr>
                <th>Item Name</th>
                
                <th>Price</th>
                <th colspan="2">Action</th>
            </tr>
        </thead>

        <tbody>
            
            <tr><td colspan="3" class="text-center bg-danger text-light"><h4>Soup</h4></td></tr>
            @foreach(var item in @ViewBag.Soup)
            {
                <tr>
                    <td>@item.ItemName </td>
                    
                    <td>@item.Price</td>
                    <td>
                        <form asp-controller="Item" asp-action="DeleteItem" method="post">
                            <input type="hidden" name="itemId" value="@item.ItemId">
                            <button type="submit" class="btn btn-primary">Delete</button>                   
                        </form>
                    </td>
                </tr>
            }
            <tr><td colspan="3" class="text-center bg-danger text-light"><h4>Starter</h4></td></tr>
            @foreach(var item in @ViewBag.Starter)
            {
                <tr>
                    <td>@item.ItemName </td>
                    
                    <td>@item.Price</td>
                    <td>
                        <form asp-controller="Item" asp-action="DeleteItem" method="post">
                            <input type="hidden" name="itemId" value="@item.ItemId">
                            <button type="submit" class="btn btn-primary">Delete</button>                   
                        </form>
                    </td>
                </tr>
            }

             <tr><td colspan="3" class="text-center bg-danger text-light"><h4>Main Course</h4></td></tr>
            @foreach(var item in @ViewBag.MainCourse)
            {
                <tr>
                    <td>@item.ItemName </td>
                    
                    <td>@item.Price</td>
                    <td>
                        <form asp-controller="Item" asp-action="DeleteItem" method="post">
                            <input type="hidden" name="itemId" value="@item.ItemId">
                            <button type="submit" class="btn btn-primary">Delete</button>                   
                        </form>
                    </td>
                </tr>
            }

            <tr><td colspan="3" class="text-center bg-danger text-light"><h4>Dessert</h4></td></tr>
            @foreach(var item in @ViewBag.Dessert)
            {
                <tr>
                    <td>@item.ItemName </td>
                    
                    <td>@item.Price</td>
                    <td>
                        <form asp-controller="Item" asp-action="DeleteItem" method="post">
                            <input type="hidden" name="itemId" value="@item.ItemId">
                            <button type="submit" class="btn btn-primary">Delete</button>                   
                        </form>
                    </td>
                </tr>
            }

            <tr><td colspan="3" class="text-center bg-danger text-light"><h4>Beverages</h4></td></tr>
            @foreach(var item in @ViewBag.Beverages)
            {
                <tr>
                    <td>@item.ItemName </td>
                    
                    <td>@item.Price</td>
                    <td>
                        <form asp-controller="Item" asp-action="DeleteItem" method="post">
                            <input type="hidden" name="itemId" value="@item.ItemId">
                            <button type="submit" class="btn btn-primary">Delete</button>                   
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else {
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <strong>Please Login...</strong>
       <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}
//

RestaurantManagement/Views/Item/ViewAllOrders.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor Accessor

@model List<Order>

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{

}

@if(Accessor.HttpContext.Session.GetString("SUserName") != null)
{
    <div class="container">

        <table class="table table-striped">

            <thead>
                <tr>
                    <th>OrderId</th>
                    <th>Customer Name</th>
                    <th>Order Type</th>
                    <th>Order Status</th>
                    <th>Payment Status</th>
                    <th>OrderDate</th>
                </tr>
            </thead>

            <tbody>
                @foreach(var order in @Model)
                {
                    <tr>
                        <td>@order.OrderId</td>
                        <td>@order.CustomerName</td>
                        <td>@order.OrderType</td>
                        <td>@order.OrderStatus</td>
                        <td>@order.PaymentStatus</td>
                        <td>@order.OrderDate</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else {
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <strong>Please Login...</strong>
       <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}
//

RestaurantManagement/Views/Item/ViewBill.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor Accessor

@model Order

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    var total = 0;
}

<style>
    .billDetails, .btns{
        display: flex;
        justify-content: space-between;
        
    }

    .bill {
        border: 2px solid black;
    }
</style>

@if(Accessor.HttpContext.Session.GetString("SUserName") != null)
{
    <div class="bill p-5">

        <div class="billDetails">
            <div class="Restaurant-details">
                <h4>Food Hut</h4>
                <p>Phone no: 123-456-789</p>
                <p>Email: foodhut2022@@gmail.com</p>
                <pre>Address: AppleView Complex
College road, Nadiad
                </pre>
            </div>

            <div class="Orders-details">
                <h4>Order Id: @Model.OrderId</h4>
                <p>Customer Name: @Model.CustomerName</p>
                <p>Order Date: @Model.OrderDate</p>

            </div>

        </div>
        <div class="container">
        
            <table class="table table-striped">      
                    <tr>
                        <th>Item</th>
                        <th>Quantity</th>
                        <th>Unit Price</th>
                        <th>Amount</th>
                    </tr>      
                    @foreach(var item in @ViewBag.ordItems)
                    {
                    <tr>
                        @{
                            var amount = item.Quantity * item.UnitPrice;
                            total += amount;
                        }
                            <td>@item.OrderedItem</td>
                            <td>@item.Quantity</td>
                            <td>@item.UnitPrice</td>
                            <td>@amount</td>
                    
                        </tr>
                    }
                    <tr>
                        <td></td>
                        <td></td>
                        <td>Total Amount:</td>
                        <td>@total</td>
                    </tr>
                    
            </table>
            <div class="btns">
                <button onclick="window.print()" class="btn btn-danger">Print</button>
                <a class="btn btn-danger" asp-area="" asp-controller="User" asp-action="Index" style="color: white">Back to home</a>

            </div>
        </div>
    </div>

    
}
else {
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <strong>Please Login...</strong>
       <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}
//

RestaurantManagement/Views/Item/ViewPendingOrders.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor Accessor

@model List<Order>

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@if(Accessor.HttpContext.Session.GetString("SUserName") != null)
{
    
    <div class="container">

        <table class="table table-striped">

            <thead>
                <tr>
                    <th>OrderId</th>
                    <th>Customer Name</th>
                    <th>OrderType</th>
                    <th>OrderStatus</th>
                    <th>OrderDate</th>
                    <th>Action</th>
                </tr>
            </thead>

            <tbody>
                @foreach(var order in @Model)
                {
                    <tr>
                        <td>@order.OrderId</td>
                        <td>@order.CustomerName</td>
                        <td>@order.OrderType</td>
                        <td>@order.OrderStatus</td>
                        <td>@order.OrderDate</td>
                        <td>
                             <form asp-controller="Item" asp-action="changeOrderStatus" method="post">
                                 <input type="hidden" name="orderId" value="@order.OrderId"/>
                                 <input type="submit" name="submit" value="served" />
                             </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else {
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <strong>Please Login...</strong>
       <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}
//

RestaurantManagement/Views/Item/ViewPendingPayments.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor Accessor

@model List<Order>

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@if(Accessor.HttpContext.Session.GetString("SUserName") != null)
{
    
    <div class="container">

        <table class="table table-striped">

            <thead>
                <tr>
                    <th>OrderId</th>
                    <th>Customer Name</th>
                    <th>OrderType</th>
                    <th>OrderStatus</th>
                    <th>OrderDate</th>
                    <th>Action</th>
                </tr>
            </thead>

            <tbody>
                @foreach(var order in @Model)
                {
                    <tr>
                        <td>@order.OrderId</td>
                        <td>@order.CustomerName</td>
                        <td>@order.OrderType</td>
                        <td>@order.OrderStatus</td>
                        <td>@order.OrderDate</td>
                        <td>
                             <form asp-controller="Item" asp-action="changePaymentStatus" method="post">
                                 <input type="hidden" name="orderId" value="@order.OrderId"/>
                                 <input type="submit" name="submit" value="Paid" />
                             </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else {
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <strong>Please Login...</strong>
       <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}
//